-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''
    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

-- Color definitions
local Color15 = '#81858d'
local Color7 = '#a179fb'
local Color2 = '#00bc03'
local Color16 = '#000815'
local Color9 = '#030c1b'
local Color14 = '#535172'
local Color11 = '#212e26'
local Color0 = '#16b87b'
local Color4 = '#ff00d7'
local Color1 = '#af00ff'
local Color3 = '#67caff'
local Color5 = '#ffcf67'
local Color13 = '#264f78'
local Color6 = '#fb5474'
local Color8 = '#ffffff'
local Color10 = '#00112a'
local Color12 = '#350915'

-- Base highlights
highlight('Normal', Color9, Color0, nil)
highlight('Comment', nil, Color14, 'italic')

-- Syntax highlighting
highlight('Operator', nil, Color0, nil)
highlight('Keyword', nil, Color1, nil)
highlight('Identifier', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Type', nil, Color4, nil)  -- Removed duplicate
highlight('Conditional', nil, Color1, nil)
highlight('Repeat', nil, Color1, nil)
highlight('String', nil, Color5, nil)
highlight('Number', nil, Color6, nil)
highlight('Constant', nil, Color6, nil)

-- UI elements
highlight('StatusLine', Color8, Color7, nil)
highlight('WildMenu', Color9, Color0, nil)
highlight('Pmenu', Color9, Color0, nil)
highlight('PmenuSel', Color0, Color10, nil)
highlight('PmenuThumb', Color9, Color0, nil)
highlight('Visual', Color13, nil, nil)
highlight('CursorLine', Color13, nil, nil)
highlight('ColorColumn', Color13, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color14, nil)

-- Diff highlighting
highlight('DiffAdd', Color11, nil, nil)
highlight('DiffDelete', Color12, nil, nil)

-- Tab line
highlight('TabLine', Color16, Color15, nil)
highlight('TabLineSel', Color8, Color10, nil)
highlight('TabLineFill', Color16, Color15, nil)

-- Custom highlights for links
highlight('MyTag', nil, Color4, nil)
highlight('MyBracket', nil, Color0, nil)

-- TreeSitter highlights
highlight('TSPunctDelimiter', nil, Color0, nil)

-- Links
link('TSConditional', 'Conditional')
link('TSConstant', 'Constant')
link('TSRepeat', 'Repeat')
link('TSTagDelimiter', 'Type')
link('TSProperty', 'TSField')
link('Whitespace', 'Comment')
link('TSNumber', 'Number')
link('TSLabel', 'Type')
link('TSParameter', 'Constant')
link('TSComment', 'Comment')
link('NonText', 'Comment')
link('TSFuncMacro', 'Function')
link('TSString', 'String')
link('TelescopeNormal', 'Normal')
link('Folded', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSKeyword', 'Keyword')
link('TSFloat', 'Number')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSNamespace', 'Type')
link('TSTag', 'MyTag')
link('TSField', 'Constant')
link('TSParameterReference', 'TSParameter')
link('TSOperator', 'Operator')
link('TSFunction', 'Function')
link('TSConstBuiltin', 'Constant')
link('TSPunctBracket', 'MyTag')
link('TSType', 'Type')

-- Additional useful links
link('Macro', 'Function')
link('Special', 'Keyword')
link('SpecialChar', 'Special')
link('Tag', 'MyTag')
link('Delimiter', 'TSPunctDelimiter')
link('SpecialComment', 'Comment')
link('Debug', 'Special')
